### PR TITLE
Fix Fiat Rate Service

### PR DESCRIPTION
**Pull request by snogcel**

### CODE REVIEW

**Review by lilienblum — CHANGES_REQUESTED** [review]
This fix will not help because coinmarketcap will respond with real-time rate but we need historical rate

**Comment by snogcel** [comment]
That's a good catch but I think in this case it should be okay because BWS stores historical exchange rates in a mongodb table which is populated using a timed / cron job. When the "/v1/fiatrates/USD" route is called BWS will query local storage: https://github.com/dashevo/bitcore-wallet-service-dash/blob/master/lib/fiatrateservice.js#L120-L129

For example:

When the following API is called http://10.1.10.101:3232/bws/api/v1/fiatrates/USD/?ts=1532035962000 (Thursday, July 19, 2018 9:32:42 PM GMT) I end up receiving this response: {"ts":1532035962000,"rate":"259.08","fetchedOn":1532035948340}. This is accurate even though the BTC exchange rate has changed since then. I can stage this PR on a test server if you'd like, let me know what you think.

**Review by lilienblum — APPROVED** [review]

**Comment by lilienblum** [comment]
@snogcel ah got it. this fix will work for new transactions but what about the old ones?

**Comment by snogcel** [comment]
Unfortunately the old entries in MongoDB will still carry the inaccurate (btc) value. Short of some sort of query to transform these to Dash pricing (would be hard to do as the dash -> btc exchange rate is dynamic) there's not a good way to get prior data.

**Pull request merged**
