### PR TITLE
Merge Upstream

### PR DESCRIPTION
**Pull request by snogcel**
This PR brings Bitcore Wallet Service current with upstream changes from Bitpay.

### CODE REVIEW

**Comment by nmarley** [comment]
Thanks for the update @snogcel ! This is really big. Can we get smaller PRs in the future?

I'd like to follow the [DashCore guidelines for PRs](https://github.com/dashpay/dash/blob/master/CONTRIBUTING.md#pull-request-philosophy), esp:

> Patchsets should always be focused. For example, a pull request could add a feature, fix a bug, or refactor code; but not a mixture. Please also avoid super pull requests which attempt to do too much, are overly large, or overly complex as this makes review difficult.

This helps keep our diffs smaller and is much easier to review.

**Comment by snogcel** [comment]
My pleasure @nmarley this was a little bit trickier since it was pulling about 6+ months of upstream BitPay stuff -- will definitely try to keep these smaller in the future but wasn't quite sure how else to approach it in this case. The answer may lie in simply merging these upstream changes more frequently to make them more palatable :-)

**Comment by nmarley** [comment]
Yeah, probably a good idea. :D

I know that for Core, they're merging backports in several batches and backporting each PR from the upstream repo, so that might be one strategy we could try going forward.

**Review by lilienblum — APPROVED** [review]
Lgtm. Should be tested before merge

**Comment by snogcel** [comment]
performed additional testing and found a couple small issues with InstantSend transaction broadcasting, should be good to go at this point.

**Pull request merged**
